[lint]
select = ["ALL"]
ignore = [
    "D203",    # Incompatible with D211
    "TD003",   # missing issue link in TODO
    "TD004",   # missing version in TODO
    "TD005",   # missing description in TODO
    "FIX002",  # line contains TODO
    "PLR2004", # magic value 404
    "D212",    # Multiline docstring
    "E501",    # Line too long
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
    "BLE001",  # Blind exception catching
    "FBT001",  # Boolean-typed positional argument in function definition
    "ARG001",  # Unused argument
    "ANN401",  # Dynamically typed expressions (typing.Any) are disallowed
    "COM812",  # Incompatible with formatter
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25